---
driver:
  forward_agent: yes
  name: vagrant
  vm_hostname: false # do not bother trying to change the hostname (sometimes fails)
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm

verifier:
  name: inspec

provisioner:
  name: chef_zero

driver_config:
  subscription_id: "1e0b427a-d58b-494e-ae4f-ee558463ebbf"
  #location: "West US"
  location: "japaneast"
  machine_size: "Standard_D2"
  image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest

platforms:
  - name: win2012-r2-azure
    driver:
      name: azurerm
  - name: win2012-r2-asure
    run_list:
      - recipe[fourthcoffee::blank]
    driver:
      name: azurerm

suites:
- name: default
  run_list:
    - 'recipe[fourthcoffee]'
  attributes:
    fourthcoffee:
      install_method: _dsc
