---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV["EC2_SSH_KEY_NAME"] %>
  region: us-west-2
  availability_zone: us-west-2c
  security_group_ids: sg-401e0e25
  iam_profile_name: testKitchenAndKnifeEc2
  subnet_id: subnet-5b32ef02
  instance_type: m3.large
  associate_public_ip: true
  user_data: 'windows_user_data'
  tags:
    Name: "fourthcoffee-localdev-kitchen-instance"
    created-by: "test-kitchen"
    user: <%= ENV['USER'] %>
    X-Dept: Sales
    X-Contact: <%= ENV['USER'] %>
    X-Production: "false"

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36

verifier:
  name: inspec

platforms:
  - name: windows-2016
    driver_config:
      image_id: ami-94e26af4
    transport:
      ssh_key: <%= ENV["EC2_SSH_KEY_PATH"] %> # change it; this is needed so kitchen can retrieve the Admin password

suites:
  - name: default
    run_list:
      # The test cookbook is located in test/fixtures.
      # It is what puts secret keys, certs, etc. in place
      - recipe[fourthcoffee::default]
    # attributes:
    #   demo:
    #     domain_prefix: ''
    #     domain: 'automate-demo.com'
    #     enterprise: 'automate-demo'
    #     org: 'automate'
    #     hosts:
    #     workstations: 1
    #     workstation-number: 1
    #     versions:
    #       chefdk: 'stable-1.2.22'
    verifier:
      inspec_tests:
        - test/integration/default/inspec/controls
